version: 2

defaults: &defaults
  working_directory: /go/src/github.com/weaveworks/Watch
  docker:
    - image: circleci/golang:latest

jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: ./gok.sh


  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run: |
          ssh remote-docker \<<EOF
            sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
            sudo systemctl restart docker
          EOF
      - run: go build
      - run: |
          docker buildx create --use
      - deploy:
          name: push image
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" docker.io
              docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --push --tag "docker.io/weaveworks/watch:$(./image-tag)" .
              docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --push --tag "docker.io/weaveworks/watch" .
            fi


workflows:
  version: 2
  build_deploy:
    jobs:
      - tests
      - build
