version: 2.1

workflows:
  build_deploy:
    jobs:
      - tests
      - build

jobs:
  tests:
    working_directory: /go/src/github.com/weaveworks/Watch
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: ./gok.sh

  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run: docker buildx create --use
      - run: |
          docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag "docker.io/weaveworks/watch:$(./image-tag)" .
      - deploy:
          name: push image
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" docker.io
              docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --push --tag "docker.io/weaveworks/watch:$(./image-tag)" .
              docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --push --tag "docker.io/weaveworks/watch" .
            fi
