name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yaml

  release:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
      GO_VERSION: 1.19
    steps:
      - name: Login to GitHub packages
        uses: docker/login-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          # This is a token automatically added to actions by Github. It is used to create releases and upload artifacts as release assets.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
